"""add authentication fields

Revision ID: 9670e843ebab
Revises: 5c5be77c1a07
Create Date: 2026-08-27 13:27:02.713718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9670e843ebab'
down_revision: Union[str, Sequence[str], None] = '5c5be77c1a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column(
        'password_hash',
        sa.String(),
        nullable=False,
        server_default="TEMP_PASSWORD_CHANGE"
    )
)
    op.add_column(
    'users',
    sa.Column(
        'role',
        sa.String(),
        nullable=False,
        server_default="lawyer"
    )
)
    op.add_column(
    'users',
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=True
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
