"""expand case management fields

Revision ID: b2a44c77fcf9
Revises: 9670e843ebab
Create Date: 2026-08-27 16:02:08.260936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a44c77fcf9'
down_revision: Union[str, Sequence[str], None] = '9670e843ebab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('cnic', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('police_station', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('status', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'lawyer'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'lawyer'::character varying"))
    op.drop_column('cases', 'created_at')
    op.drop_column('cases', 'status')
    op.drop_column('cases', 'police_station')
    op.drop_column('cases', 'cnic')
    # ### end Alembic commands ###
